### ISSUE TITLE
Regarding the voice authentication

### ISSUE THREAD

**Issue by nagapoornima22** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#14]
Hi Mohamad,

Thank you very much for your contribution of Voice-Authentication-and-Face-Recognition project on Github. I tried by adding the 2 users. when we are not saying anything also it is showing one of the users. Please can you help me in avoiding this. If there is no voice recording it should prompt me as not recorded instead of giving me one of the users.

**Comment by MohamadMerchant** [comment]
Hi,
For multiple users you need to record samples in a clear background for better predictions and if there are no voice samples it will show Not Recognized! Try Again...instead of giving user's name.
try 'running recognize_until_keyboard_interrupt.py' for continuous recognition as for multiple users, if some times the prediction probability is above the threshold, it will recognize after one or two times.

**Comment by nagapoornima22** [comment]
Thank You
